// <auto-generated />
using System;
using MessengerData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessengerData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221017115537_MessageCommentNotICollection")]
    partial class MessageCommentNotICollection
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MessengerModel.ChatModelds.Chat", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Public")
                        .HasColumnType("bit");

                    b.HasKey("Guid");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("MessengerModel.DeletedMessage", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MessageGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Date", "MessageGuid", "ChatGuid", "UserGuid");

                    b.HasIndex("ChatGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("DeletedMessage");
                });

            modelBuilder.Entity("MessengerModel.MessageComment", b =>
                {
                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MessageGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommentedMessageDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CommentedMessageGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MessageDate", "MessageGuid");

                    b.HasIndex("CommentedMessageDate", "CommentedMessageGuid");

                    b.ToTable("MessageComment");
                });

            modelBuilder.Entity("MessengerModel.MessageModels.Message", b =>
                {
                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ChatGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Date", "Guid");

                    b.HasIndex("ChatGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MessengerModel.UserChats", b =>
                {
                    b.Property<Guid>("ChatGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChatGuid", "UserGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("UserChats");
                });

            modelBuilder.Entity("MessengerModel.UserContacts", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserGuid", "ContactGuid");

                    b.HasIndex("ContactGuid");

                    b.ToTable("UserContacts");
                });

            modelBuilder.Entity("MessengerModel.UserModels.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MessengerModel.DeletedMessage", b =>
                {
                    b.HasOne("MessengerModel.ChatModelds.Chat", "Chat")
                        .WithMany("DeletedMessages")
                        .HasForeignKey("ChatGuid")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("MessengerModel.UserModels.User", "User")
                        .WithMany("DeletedMessages")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("MessengerModel.MessageModels.Message", "Message")
                        .WithMany()
                        .HasForeignKey("Date", "MessageGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessengerModel.MessageComment", b =>
                {
                    b.HasOne("MessengerModel.MessageModels.Message", "CommentedMessage")
                        .WithMany()
                        .HasForeignKey("CommentedMessageDate", "CommentedMessageGuid")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("MessengerModel.MessageModels.Message", "Message")
                        .WithOne("MessageComment")
                        .HasForeignKey("MessengerModel.MessageComment", "MessageDate", "MessageGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentedMessage");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MessengerModel.MessageModels.Message", b =>
                {
                    b.HasOne("MessengerModel.ChatModelds.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatGuid")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("MessengerModel.UserModels.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessengerModel.UserChats", b =>
                {
                    b.HasOne("MessengerModel.ChatModelds.Chat", "Chat")
                        .WithMany("ChatUsers")
                        .HasForeignKey("ChatGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessengerModel.UserModels.User", "User")
                        .WithMany("UserChats")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessengerModel.UserContacts", b =>
                {
                    b.HasOne("MessengerModel.UserModels.User", "Contact")
                        .WithMany("IAsContact")
                        .HasForeignKey("ContactGuid")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("MessengerModel.UserModels.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessengerModel.ChatModelds.Chat", b =>
                {
                    b.Navigation("ChatUsers");

                    b.Navigation("DeletedMessages");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MessengerModel.MessageModels.Message", b =>
                {
                    b.Navigation("MessageComment");
                });

            modelBuilder.Entity("MessengerModel.UserModels.User", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("DeletedMessages");

                    b.Navigation("IAsContact");

                    b.Navigation("Messages");

                    b.Navigation("UserChats");
                });
#pragma warning restore 612, 618
        }
    }
}
